# PRESET_BASE:
# TERMINAL_TOTAL_DIFFICULTY:
# MIN_GENESIS_ACTIVE_VALIDATOR_COUNT:
# MIN_GENESIS_TIME:
# GENESIS_FORK_VERSION:
# GENESIS_DELAY:

ALTAIR_FORK_VERSION: "0x01000001"
ALTAIR_FORK_EPOCH: "1"
BELLATRIX_FORK_VERSION: "0x02000001"
BELLATRIX_FORK_EPOCH: "2"

# SECONDS_PER_SLOT:
# SECONDS_PER_ETH1_BLOCK:

# The lower the value is, the more percentage of validators can enter and exit
CHURN_LIMIT_QUOTIENT: "32"
# DEPOSIT_CHAIN_ID:
# DEPOSIT_NETWORK_ID:
# DEPOSIT_CONTRACT_ADDRESS:

# Same as mainnet
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: "256"
ETH1_FOLLOW_DISTANCE: "1"
INACTIVITY_SCORE_BIAS: "4"
INACTIVITY_SCORE_RECOVERY_RATE: "16"
EJECTION_BALANCE: "16000000000"
MIN_PER_EPOCH_CHURN_LIMIT: "4"
PROPOSER_SCORE_BOOST: "40"
SAFE_SLOTS_TO_IMPORT_OPTIMISTICALLY: "128"
SHARD_COMMITTEE_PERIOD: "256"
TERMINAL_BLOCK_HASH: "0x0000000000000000000000000000000000000000000000000000000000000000"
TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: "18446744073709551615" # max of u64

# After this line should be auto-generated
